Add NXP.PCF8563 impl, and fix NXP.PCA8565
nerves-time/nerves_time_rtc_nxp pull request #4
Opened 2023-05-25 07:05 UTC by pojiro

2023-05-25 07:14 UTC, pojiro commented on lib/nerves_time/rtc/nxp/pca8565.ex
> +
[Calendar.ISO.day_of_week](https://hexdocs.pm/elixir/1.14.5/Calendar.ISO.html#day_of_week/4) returns `1..7` for weekdays.

So `day_of_week`, 1..7 should be decriment 1 for devive.

PCA8565, PCF8563 both uses `0..6` for weekdays, 0 is sunday for both device.

refs. 
https://www.nxp.com/docs/en/data-sheet/PCA8565.pdf, sec. 8.4.5
https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf, sec. 8.4.5

2023-05-25 07:20 UTC, pojiro commented on lib/nerves_time/rtc/nxp/pca8565.ex
> +    end
`set_time` and `get_time` returns should be match behaviour I/F, so I fixed.

2023-05-27 23:25 UTC, pojiro commented
@fhunleth @ConnorRigby Could you review this when you are free?

2023-05-27 23:37 UTC, fhunleth commented
Hi @pojiro - Thanks for the PR and for at-ing me since I didn't get the notification. I don't have this RTC. Let me see if Connor is still using it. Would you mind if I gave you access to this repository to help maintain it? You might be using it more than us right now.

2023-05-27 23:46 UTC, ConnorRigby requested changes
I don't have hardware to test it unfortunately, but this is a very good looking PR. I checked the linked datasheets and it looks correct to me on face value. It feels good to merge to me. Would you mind squashing the commits?

2023-05-27 23:49 UTC, pojiro commented
@fhunleth @ConnorRigby Thanks for quick reply.

> Would you mind if I gave you access to this repository to help maintain it?

> Would you mind squashing the commits?

Both, I don't mind. Thanks to give me a chance to contribute :)

2023-05-28 12:35 UTC, pojiro commented
@ConnorRigby I squashed commits to one.

2023-05-30 02:06 UTC, ConnorRigby approved these changes

2023-05-30 02:06 UTC, merged